# ==================================================================================================================
#
# Docker to ubuntu 16.04 image for Moja flint libraries and executables
#
# Building this Docker: 
#   docker build  -f Dockerfile.flint.ubuntu.18.04 --build-arg NUM_CPU=4 --build-arg GITHUB_AT=[TOKEN] --build-arg FLINT_BRANCH=[BRANCH] -t moja/flint:ubuntu-18.04 .
#
# ==================================================================================================================

FROM moja/baseimage:ubuntu-18.04

LABEL maintainer="info@moja.global"

ARG GITHUB_AT
ARG FLINT_BRANCH
ARG NUM_CPU=1
ARG DEBIAN_FRONTEND=noninteractive
ENV POCO_VERSION 1.9.2
ENV SQLITE_VERSION 3370200
ENV ROOTDIR /usr/local/

WORKDIR $ROOTDIR/

# set environment variables
ENV PATH /usr/local/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
ENV PYTHONPATH /usr/local/lib:$PYTHONPATH
ENV CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt
ENV GDAL_DATA=/usr/share/gdal
ENV GDAL_HTTP_VERSION 2

RUN apt-get install -y postgresql-client-10 \
    postgresql-server-dev-10 \
    && apt-get -y autoremove \
    && 	apt-get clean 

ADD https://www.sqlite.org/2022/sqlite-autoconf-${SQLITE_VERSION}.tar.gz $ROOTDIR/src/
RUN cd src && tar -xzf sqlite-autoconf-${SQLITE_VERSION}.tar.gz -C /usr/local/ \
	&& cp /usr/local/sqlite-autoconf-${SQLITE_VERSION}/sqlite3.c /usr/include/ \
    && cd $ROOTDIR && rm -Rf src/sqlite*

RUN wget https://pocoproject.org/releases/poco-${POCO_VERSION}/poco-${POCO_VERSION}-all.tar.gz \
    && tar -xzf poco-${POCO_VERSION}-all.tar.gz \
	&& mkdir poco-${POCO_VERSION}-all/cmake-build \
	&& cd poco-${POCO_VERSION}-all/cmake-build \
	&& cmake -DCMAKE_BUILD_TYPE=RELEASE \
			 -DCMAKE_INSTALL_PREFIX=$ROOTDIR \
			 -DPOCO_UNBUNDLED=ON \
			 -DPOCO_STATIC=OFF \
			 -DENABLE_ENCODINGS=OFF \
			 -DENABLE_ENCODINGS_COMPILER=OFF \
			 -DENABLE_XML=OFF \
			 -DENABLE_JSON=ON \
			 -DENABLE_MONGODB=OFF \
			 -DENABLE_REDIS=OFF \
			 -DENABLE_PDF=OFF \
			 -DENABLE_UTIL=OFF \
			 -DENABLE_NET=OFF \
			 -DENABLE_NETSSL=OFF \
			 -DENABLE_CRYPTO=OFF \
			 -DENABLE_DATA=ON \
			 -DENABLE_DATA_SQLITE=ON \
			 -DENABLE_DATA_MYSQL=OFF \
			 -DENABLE_DATA_ODBC=OFF \
			 -DENABLE_SEVENZIP=OFF \
			 -DENABLE_ZIP=OFF \
			 -DENABLE_PAGECOMPILER=OFF \
			 -DENABLE_PAGECOMPILER_FILE2PAGE=OFF \
			 -DENABLE_TESTS:BOOL=OFF .. \
	&& make --quiet -j $NUM_CPU \
    && make --quiet install/strip \
    && make clean \
    && cd $ROOTDIR/src

# GET FLINT
WORKDIR $ROOTDIR/
RUN cd src && git clone -b ${FLINT_BRANCH} https://${GITHUB_AT}@github.com/moja-global/flint.git flint
                                          
WORKDIR $ROOTDIR/src/flint/Source/build
RUN cmake   -DCMAKE_BUILD_TYPE=RELEASE \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DENABLE_MOJA.MODULES.ZIPPER=ON \
            -DENABLE_MOJA.MODULES.POCO=OFF \
            -DENABLE_MOJA.MODULES.LIBPQ=ON \
            -DENABLE_MOJA.MODULES.GDAL=ON \
            -DENABLE_MOJA.CLI=ON \
            -DENABLE_TESTS:BOOL=OFF .. \
	&& make -s -j $NUM_CPU \
	&& make install \
	&& make clean

WORKDIR $ROOTDIR/src

RUN ln -s /usr/local/lib/libmoja.modules.* /usr/local/bin	
RUN rm -Rf /usr/local/src/*
WORKDIR /tmp/flint_runenv
