name: Build Source Docs

on:
  push:
    branches: [ source-docs ]

jobs:
  build-source-docs:
    runs-on: ubuntu-latest  
    name: Build Source Documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Sphinx docs
        run: |
          sudo apt-get install python3-sphinx
          sudo apt-get install doxygen
          pip install sphinx-sitemap
          pip install breathe
          pip install sphinx-rtd-theme
          cd Source/docs_sphinx
          make html
     
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'Source/docs_sphinx/_build/html'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 3